#!/bin/zsh

# Copyright (c) 2015 University of Waterloo
#
# The contents of this file are covered under the licence agreement in 
# the file "LICENCE" distributed with this repository.

if [ "$#" -ne 1 ]; then
	echo "usage: $0 <mode>" >&2
	exit 1
fi

new=( out/$1-*.csv(om[1]) )
old=( out/$1-*.csv(om[2]) )

if [[ ! -d plots ]]; then mkdir plots; fi

gnuplot -e "new='${new}'; old='${old}'; mode='$1'" gen_comp_plots.gp
