#!/bin/zsh

# Copyright (c) 2015 University of Waterloo
#
# The contents of this file are covered under the licence agreement in 
# the file "LICENCE" distributed with this repository.

#grab modes from arguments
if [ $# -eq 0 ]; then 
	# grabs all CSVs in output directory, strips prefix and suffix, then keeps unique
	modes=(`ls out/*.csv | sed -e 's/^out\/[[:digit:]]*-[[:alnum:]]*-//' -e 's/\.csv$//' | sort -u`)
else
	modes=("$@")
fi

# read most recent output file for each mode
files=()
for m in "${modes[@]}"; do
	files+=( out/*-$m.csv(om[1]) )
done

# ensure plots directory exists
if [[ ! -d plots ]]; then mkdir plots; fi

# generate plots
gnuplot -e "n=${#modes[@]}; files='$files'; labels='$modes'" gen_plots.gp
